### ISSUE TITLE
Save to host?

### ISSUE THREAD

**Issue by fredrikakesson** [esskar/Canon.Eos.Framework#2]
Hi

I'm trying to save pictures to host, using your sample code but with the following changes:

try
{
    camera.SavePicturesTo = EosCameraSavePicturesTo.Host;
    camera.SavePicturesToHostLocation(@"c:\temp\camera\");

```
camera.TakePicture();
```

}

The folder is created and the camera snaps an image but no file is created. Am I doing it wrong?

I'm using an EOS600D, Windows XP and Visual Studio 2010.

Nonetheless, awesome work!

**Comment by esskar** [comment]
i am on vaction right now, let me get back to you by next week

**Comment by esskar** [comment]
you are right. i behaves strange when run from an command line.
i think for the event triggering to work, it has to run on a different thread, but not sure.
I added a sample solution to the project. A lot of features missing but i will try to smooth it up during the upcoming week.
Feel free to test and report bugs. Thanks for the feedback.

**Comment by hannesjung** [comment]
hi esskar!
first of all - thank you so much for all your effort that you put into this! your framework is exactly what i was looking for.
i have a question concerning the savePicturesToHost functionality:

i'm trying to capture a picture with my canon 5d mark ii and then save it to a folder. this is what i have so far:

``` c#
var framework = new EosFramework();
var cameras = framework.GetCameraCollection();

  foreach (var camera in cameras)
  {
    Console.WriteLine("Connected to {0}", camera.DeviceDescription);
    try
    {
      camera.SavePicturesToHost("./pictures/");
      camera.TakePicture();
    }
    catch (EosException eos)
    {
      Console.Error.WriteLine("Last Command Failed with error {0}, {1}", eos.EosErrorCode, eos);
      Console.ReadLine();
    }
  }
```

when `camera.SavePicturesToHost("./pictures/");` the folder gets created but the pictures don't appear. however the pictures i took in the previous try get stored in the root folder sometimes.

before that i tried to add an eventhandler for `camera.PictureTaken` but it never got called, i also didn't get it to work with another thread. I would be glad if you could help me.

thanks again for such a great framework!
hannes

**Comment by esskar** [comment]
yes, i have noticed that my self. but it only happens if you run this from the command line.
the EDSDK seems to use a strange threading model or depends on running in an own thread: i have to figure that out.
but it should work when running from a WinForms or WPF application
