### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Bill-Lea** [esskar/Canon.Eos.Framework#6]
I have obtained a new copy of the code. I get errors when I try and compile it under the C# express version of Visual Studio  2008.  The error is given as " Default parameter Specifiers are not permitted" the framework code contains three instances of this error.  My question is does this code require a version of c# professional to compile? I have tried removing the default specifier and simply get additional errors relating to number of constructor arguments. Can you give me some advise as to the minimum compiler package needed to handle this code? 
Thanks

**Comment by esskar** [comment]
hi, i think you need visual studio express 2010 since the code is c# 4.0
unfortunatly i do not have time to build a VS 2008 compatible version
at this time.

2012/2/6 Bill-Lea
reply@reply.github.com:

**Comment by Bill-Lea** [comment]
You are correct. Sorry for dumb question. When I go to my desktop system I get a clean compile and a good functional test. You might consider setting the picture box to zoom so that the whole image is visible.
It's very impressive. 

 My problem is that I want to run it on an Acer1 Netbook which is the computer I use in the field. The other camera I want to control has a library which seems to require XP (so they say) I'll need to test that too. I'm not sure if this 32 bit XP system will support VS2010 and.Net 4.0.  I will see if it will.  

If necessary I will port it to VS2008 net 3.5. How hard can it be? It looks  like you have done most of the work.
I need to get something that will fit in the ASCOM camera driver format. 

You indicated in a previous post you might address the camera property problem. I was wondering if you had?
