### ISSUE TITLE
missing Eventing\EosExceptionEventArgs.cs

### ISSUE THREAD

**Issue by LBee** [esskar/Canon.Eos.Framework#8]
The latest version lost this file: Eventing\EosExceptionEventArgs.cs.

**Comment by unruledboy** [comment]
I have the same problem. I just created a EosExceptionEventArgs.cs with the following code, and it works:

using System;
using System.Drawing;
using System.IO;

namespace Canon.Eos.Framework.Eventing
{
    public class EosExceptionEventArgs : EventArgs
    {
        public Exception Exception { get; set; }
    }
}

**Comment by esskar** [comment]
fixed.
